#!/bin/sh

#enable log filtering for default syslog messages, using default logFilter.json file (modify to your liking)
if [ -s /jffs/addons/modsyslogui/logFilter.json ]; then
    logger -t mylogFilter "Mounting custom logFilter.json"
    mount -o bind /jffs/addons/modsyslogui/logFilter.json /www/ajax/logFilter.json
else
    logger -t mylogFilter "UnMount standard logFilter.json"
    umount /www/ajax/logFilter.json 2>/dev/null
fi

# Mount my own custom syslog filtering UI
logger -t mySyslogFilter "Mounting my custom Syslog filter ASP"
mount -o bind /jffs/addons/modsyslogui/Main_LogStatus_Content.asp /www/Main_LogStatus_Content.asp
