#!/bin/sh

# mount the customized logFilter.json file if it exists
if [ -s /jffs/addons/modsyslogui/logFilter.json ]; then
    logger -t modsyslogui "Mounting custom logFilter.json"
    mount -o bind /jffs/addons/modsyslogui/logFilter.json /www/ajax/logFilter.json
fi

# Mount the custom System Log page containing custom filtering capabilities if it exists
if [ -f /jffs/addons/modsyslogui/Main_LogStatus_Content.asp]; then
    logger -t modsyslogui "Mounting customized System Log page"
    mount -o bind /jffs/addons/modsyslogui/Main_LogStatus_Content.asp /www/Main_LogStatus_Content.asp
fi
