#!/bin/sh
#----------------------------------------------------------------#
#   __  __           _ ____            _             _   _ ___   #
#  |  \/  | ___   __| / ___| _   _ ___| | ___   __ _| | | |_ _|  #
#  | |\/| |/ _ \ / _` \___ \| | | / __| |/ _ \ / _` | | | || |   # 
#  | |  | | (_) | (_| |___) | |_| \__ \ | (_) | (_| | |_| || |   # 
#  |_|  |_|\___/ \__,_|____/ \__, |___/_|\___/ \__, |\___/|___|  #
#                            |___/             |___/             #           
#----------------------------------------------------------------#

#----------------------------------------------------------------#
# shellcheck disable=SC1091,SC2034,SC2155,SC3037,SC3043
#----------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------#
# Author:       kstamand
# Date:         2026-05-05
# Synopsis:     add filtering functionality to routers system log page
# Description:  Installs/uninstals filtering capabilities to the router System Log UI page
# Reference:    This script is based on Asuswrt-merlin third party addon api
#+  https://github.com/RMerl/asuswrt-merlin/wiki/Addons-API/90b49e443b8ce64e82c0970237199deff46869f5
# Documentation: https://github.com/kstamand/modsyslogui
# Credits:      Code in this script modeled after FlexQoS (Dave14305) and SpdMerlin (Jack Yaz)
#----------------------------------------------------------------------------------------------------#

# AsusWRT Merlin Addon API helper functions
. /usr/sbin/helper.sh

### Start of Script Variables
readonly SCRIPT_NAME="modsyslogui"
readonly SCRIPT_VERSION="v1.2.0"
readonly scriptVersRegExp="v[0-9]{1,2}([.][0-9]{1,2})([.][0-9]{1,2})"
readonly SCRIPT_NAME_DISPLAY="ModSyslogUI"
readonly GIT_URL="https://raw.githubusercontent.com/kstamand/modsyslogui/master"
readonly ADDON_DIR="/jffs/addons"
readonly SCRIPT_NAME_DIR="${ADDON_DIR}/${SCRIPT_NAME}"
readonly SCRIPT_INSTALL_PATH="${SCRIPT_NAME_DIR}/${SCRIPT_NAME}"
readonly SCRIPT_AUTOSTART_CMD="${SCRIPT_INSTALL_PATH} autostartup"
readonly SETTINGS_FILE="/jffs/addons/custom_settings.txt"
readonly TMP_DIR="/tmp"
readonly DEFAULT_LOGFILTER_PATH="/www/ajax/logFilter.json"
readonly CUSTOM_LOGFILTER_PATH="${SCRIPT_NAME_DIR}/logFilter.json"
readonly DEFAULT_SYSLOG_ASP_FILE="/www/Main_LogStatus_Content.asp"
readonly CUSTOM_SYSLOG_ASP_FILE="${TMP_DIR}/Main_LogStatus_Content.asp"
readonly CUSTOM_FUNCTION_FILE="${SCRIPT_NAME_DIR}/customfunction.js"
readonly CUSTOM_FILTER_FILE="${SCRIPT_NAME_DIR}/customfilter.js"
readonly CUSTOM_UI_FILE="${SCRIPT_NAME_DIR}/customui.xml"
readonly LOGFILTER_MP="/www/ajax/logFilter.json"
readonly SYSLOGPAGE_MP="/www/Main_LogStatus_Content.asp"
readonly lOG_TAG="$SCRIPT_NAME"
##---------------------------------------------------##
## v1.1.0 added debugging toggle and logging to file ##
##---------------------------------------------------##
readonly DEBUG_LOG="${SCRIPT_NAME_DIR}/${SCRIPT_NAME}_debug.txt"
DEBUG_ENABLED=0 # this must not be set to readonly
exec 3>&1 # IMPORTANT - this is necessary for log file redirection and console display to work properly throughout script
readonly CONSOLE_FD=3
##---------------------------------------------------------##
## v1.1.0 added presets configuration and management files ##
##---------------------------------------------------------##
readonly PRESET_MANAGER="$SCRIPT_NAME_DIR/preset_manager.sh"
readonly PRESET_CONF="$SCRIPT_NAME_DIR/presets.conf"
readonly WWW_PRESET_DIR="/www/user/modsyslogui/"
readonly WWW_PRESET_JSON="/www/user/modsyslogui/presets.json"

RED_TEXT='\033[31m'
GREEN_TEXT='\033[32m'
YELLOW_TEXT='\033[33m'
MAGENTA_TEXT='\033[35m'
CYAN_TEXT='\033[36m'
RESET='\033[0m'

##--------------------------------------------------------------------##
## v1.0.1 supporfed firmware version check - inspired by Martinksi W. ##
##--------------------------------------------------------------------##
readonly fwInstalledBaseVers="$(nvram get firmver | sed 's/\.//g')"
readonly fwInstalledBuildVers="$(nvram get buildno)"
readonly fwInstalledExtendNum="$(nvram get extendno)"
readonly fwInstalledBranchVer="${fwInstalledBaseVers}.$(echo "$fwInstalledBuildVers" | awk -F'.' '{print $1}')"

case "$fwInstalledBranchVer" in
    "3004.388") SUPPORTED_FIRMWARE_VERSION=true ;;
    "3006.102") SUPPORTED_FIRMWARE_VERSION=true ;;
            *) SUPPORTED_FIRMWARE_VERSION=false
esac

##---------------------------------##
## v1.2.0 amtmupdate functionality ##
##---------------------------------##
ENABLE_AMTMUPDATE=true      # true = this script support amtmupdate
AMTMUPDATE_RUN_FLAG=false   # set to true only if update function initiated by amtmupdate
CURRENT_FLOW_FILE="${SCRIPT_NAME_DIR}/.logic_v1.0" # set current logic flow version file to be created
LAST_FLOW_FILE="${SCRIPT_NAME_DIR}/.logic_v0" # set current logic flow version file to be deleted
### End of Script Variables

##------------------------------------------------------------------------------------------------##
# v1.1.0 All UI output is explicitly sent to >&3 (the screen) for debug function to work properly ##
##------------------------------------------------------------------------------------------------##
Red() { printf -- '\033[1;31m%s\033[0m\n' "${1}" >&3; }
Green() { printf -- '\033[1;32m%s\033[0m\n' "${1}" >&3; }
Yellow() { printf -- '\033[1;33m%s\033[0m\n' "${1}" >&3; }
Magenta() { printf -- '\033[1;35m%s\033[0m\n' "${1}" >&3; }
Cyan() { printf -- '\033[1;36m%s\033[0m\n' "${1}" >&3; }

log_msg() {
    # $1 = display color; $2 = msg
    display_color="$1"
    msg="$2"
    if [ "$mode" = "interactive" ]; then
        if ! $AMTMUPDATE_RUN_FLAG; then   # skip displaying progress info if called from amtm (amtmupdate)
            $display_color "$msg"
        fi
    else
        logger -t "$LOG_TAG" "$msg"
    fi
}

##----------------------------------------------------------##
## v1.1.0 replaced original debug option in order to enable ##
## capturing log output to a log file                       ##
##----------------------------------------------------------##
Enable_Debug() {
    [ "$DEBUG_ENABLED" = "1" ] && {
        log_msg "Yellow" "Debug already enabled"
        return
    }

    mkdir -p "$(dirname "$DEBUG_LOG")"
    
    # Standard ash-friendly redirection: Everything goes to log file
    exec > "$DEBUG_LOG" 2>&1
    
    set -x
    DEBUG_ENABLED=1
    printf "\n===== Debug enabled: %s =====\n" "$(date)" >>"$DEBUG_LOG"
    log_msg "Yellow" "Debug enabled and output being captured in ${DEBUG_LOG}"
} # end Enable_Debug()

##--------------------------------##
## v1.1.0 added Disable Debugging ##
##--------------------------------##
Disable_Debug() {
    [ "$DEBUG_ENABLED" = "0" ] && return

    set +x
    # Restore stdout and stderr to File Descriptor 3 (the screen)
    exec 1>${CONSOLE_FD} 2>${CONSOLE_FD}

    DEBUG_ENABLED=0
    log_msg "Yellow" "Debug disabled - see ${DEBUG_LOG}"
} # end Disable_Debug()

##-------------------------------------------------------------------------------------------------##
## v1.1.0 redirection (>&3) added to keep output on screen after adding debug to log functionality ##
##-------------------------------------------------------------------------------------------------##
Press_Enter(){
    printf "\n" >&3
    printf "Press enter to continue..." >&3
    read -r key
    return 0
} # end Press_Enter()

Main_Menu() {
    clear >&3 # v1.1.0 added redirection (>&3) in support of debug to log functionality
    # Use 'cat' to ensure banner goes to screen via FD 3
    sed -n '2,9p' "${SCRIPT_INSTALL_PATH}" >&3
    Scriptinfo
    
    # These functions now use >&3 internally
    log_msg "Cyan" "  (1) About         explain functionality"
    log_msg "Cyan" "  (2) Help          information on how to use this script"
    log_msg "Cyan" "  (3) Install       install all script files"
    log_msg "Cyan" "  (4) Update        check for script updates"
    log_msg "Cyan" "  (5) Edit          edit logFilter.json"
    log_msg "Cyan" "  (6) Disable       disable dynamic UI filtering"
    log_msg "Cyan" "  (7) Enable        enable dynamic UI filtering"
    log_msg "Cyan" "  (8) Enable Debug  enable logging to file"
    log_msg "Cyan" "  (9) Disable debug disable logging"
    log_msg "Cyan" "  (10) Uninstall    completely remove script"
    log_msg "Cyan" "  (e) Exit          exit"
    
    printf "\nMake a selection: " >&3 # v1.1.0 added redirection (>&3) in support of debug to log functionality
    read -r input
    
    case "${input}" in
        '1') clear >&3; About ;; # v1.1.0 added redirection (>&3) in support of debug to log functionality
        '2') clear >&3; Show_Help ;; # v1.1.0 added redirection (>&3) in support of debug to log functionality
        '3') Install ;;
        '4') Update; exec "${SCRIPT_INSTALL_PATH}" ;; # v1.1.0 - re-execute script to show updated ver
        '5') Edit ;;
        '6') Disable_Filter ;;
        '7') Enable_Filter ;;
        '8') Enable_Debug ;; # v1.1.0 - renamed after adding logging to file + disable_debut
        '9') Disable_Debug ;; # v1.1.0 - added toggle
        '10') Uninstall; Magenta "Thanks for using ${SCRIPT_NAME_DISPLAY} - Bye"; exit ;;
        'e'|'E'|'exit') return ;;
        *) printf "\n" >&3; log_msg "Red" "[ERROR] ${input} is not a valid option!" ;; # v1.1.0 added redirection (>&3) in support of debug to log functionality
    esac
    Press_Enter
    Main_Menu
} # end Main_Menu

About() {
    Scriptinfo
    # v1.1.0 Wrap 'cat' blocks to FD 3 so they show on screen during debug
    {
    cat <<EOF
License: ${SCRIPT_NAME_DISPLAY} is free to use under MIT license.
About: This script adds dynamic filtering to the System Log web page.
EOF
    } >&3 # v1.1.0
} # end About()

Show_Help() {
    echo -e "${CYAN_TEXT}"
    # v1.1.0 Wrap 'cat' blocks to FD 3 so they show on screen during debug
    {
    cat <<EOF
The default filtering capabilities on the Systme Log page of the router is limited to hardcoded text strings
in a file called "logFilter.json". This script adds a capability to edit that file to your likings. 

This script also updates the System Log page of the Router UI to include dynamic filtering capabilities for:
   - Include all log records, which is the default function, includes exclusions noted in logFilter.json
   - Include only log records containing the string or strings of text you chose (separate each by a comma)
     Example - to include all Skynet and Diversion log records, enter Skynet,Diversion (no spaces after comma)
   - Exlude all log records containing the string or strings of text you chose (separate each by a comma)
     Example - to exlcude all Skynet log records that where blocked, enter the string BLOCKED

For reference, the following are the default contents of the "logFilter.json" file":
    {
    "filter": [
    "already exist in UDB, can't add it",
    "not mesh client, can't update it's ip",
    "not exist in UDB, can't update it",
    "send_redir_page"
    ]
    }
EOF
    } >&3 # v1.1.0 added redirection (>&3) in support of debug to log functionality
echo -e "${RESET}"
} # end Show_Help ()

Show_ArgsHelp () {
    echo -e "${YELLOW_TEXT}"
    {
    cat <<EOF
Rerun the script with no arguments or use one of the following:
   modsyslogui menu 
   modsyslogui install"
   modsyslogui update"
   modsyslogui disable"
   modsyslogui enable"
   modsyslogui uninstall"
EOF
    } >&3 # v1.1.0 added redirection (>&3) in support of debug to log functionality
echo -e "${RESET}"
} # end Show_ArgsHelp()

Scriptinfo() {
    # Version header used in interactive sessions
    printf "\n" >&3 # v1.1.0 - to keep output on screen, after adding debug to log file capability
    log_msg "Green" "${SCRIPT_NAME_DISPLAY} ${SCRIPT_VERSION}"
    printf "\n" >&3 # v1.1.0 - to keep output on screen, after adding debug to log file capability
} # end of Scriptinfo ()

Check_Firmware() {
    log_msg "Green""   - Checking firmware support"
    if ! nvram get rc_support | grep -q am_addons; then
        log_msg "Red" "${SCRIPT_NAME_DISPLAY} requires ASUSWRT-Merlin Addon API support, check your installed Merlin version. Installation aborted."
        return 1
    fi
    if [ "$(nvram get jffs2_scripts)" != "1" ]; then
       log_msg "Red" "   - Enable JFFS custom scripts and configs is not enabled. Please enable it in the GUI. Aborting installation."
        return 1
    fi
} # end of Check_Firmware()

Download_File() {
    # Parameter options: $1 = file name to download, $2 = full path + filename to download to
    # Download file from Github once to a temp location. If the same as the destination file, don't replace.
    # Otherwise move it from the temp location to the destination.
    if curl -fsNL --retry 3 --connect-timeout 10 --max-time 12 "${GIT_URL}/${1}" -o "/tmp/${1}"; then
        if [ "$(md5sum "/tmp/${1}" | awk '{print $1}')" != "$(md5sum "${2}" 2>/dev/null | awk '{print $1}')" ]; then
            mv -f "/tmp/${1}" "${2}"
            log_msg "Green" "   - Installing $(basename "${1}")"
        else
            log_msg "Yellow" "  File $(basename "${2}") is already up-to-date"
            rm -f "/tmp/${1}" 2>/dev/null
        fi
    else
        log_msg "Red" "   [ERROR] Download of $(basename "${1}") failed. Install aborted, check for Internet performance or DNS issues"
        exit 5
    fi
} # end of Download_File()

Download_Script_Files() {
    # Parameters: None
    # download ModSyslogUI script
    Download_File "$(basename "${SCRIPT_INSTALL_PATH}")" "${SCRIPT_INSTALL_PATH}" #ModSyslogUI script
    chmod 755 ${SCRIPT_INSTALL_PATH} # make script executable

    # download custom asp function file
    Download_File "$(basename "${CUSTOM_FUNCTION_FILE}")" "${CUSTOM_FUNCTION_FILE}" #UI custom function code

    # download custom ui logic file
    Download_File "$(basename "${CUSTOM_FILTER_FILE}")" "${CUSTOM_FILTER_FILE}" #UI custom filtering code

    # download custom ui PHP file
    Download_File "$(basename "${CUSTOM_UI_FILE}")" "${CUSTOM_UI_FILE}" #UI custom xml code

    # download preset manager script
    Download_File "$(basename "${PRESET_MANAGER}")" "${PRESET_MANAGER}" #Preset manager script

    # download sample presets configuration file
    # Download_File "$(basename "${PRESET_CONF}")" "${PRESET_CONF}" #Preset configuration\list of personalized presets file 
} # end of Download_Script_Files()

Mod_Startup() {
    # Parameters: $1 - install or uninstall
    case $1 in
        'install')
            log_msg "Green" "   - Adding ${SCRIPT_NAME} services-start line"
            # check if a services-start file exists and process as follows
			if [ -f /jffs/scripts/services-start ]; then
                # delete any existing modsyslogui lines just in case
                sed -i -e '/'"${SCRIPT_NAME}"'/d' /jffs/scripts/services-start
                echo "${SCRIPT_AUTOSTART_CMD} # added by ${SCRIPT_NAME}" >> /jffs/scripts/services-start
			# a service-start file did not exist, so create one
            else
				echo "#!/bin/sh" > /jffs/scripts/services-start
                echo " " >> /jffs/scripts/services-start
                echo "${SCRIPT_AUTOSTART_CMD} # added by ${SCRIPT_NAME}" >> /jffs/scripts/services-start
				chmod 0755 /jffs/scripts/services-start
			fi
        ;;
        'uninstall')
			log_msg "Green" "   - Removing ${SCRIPT_NAME} from services-start"
            # check if services-start line exists and if so, remove any HideUIMenus lines found
            sed -i -e '/'"${SCRIPT_NAME}"'/d' /jffs/scripts/services-start
        ;;
    esac
} # end of Mod_Start()

Auto_Startup() {
    # Paraemeters: None
    # Copy default System Log ASP file to scripts addon directory
    log_msg "Green" "   - Copying Asus's default Syslog ASP page, for adding in custom filtering capabilities"
    cp -f "${DEFAULT_SYSLOG_ASP_FILE}" "$TMP_DIR/" 2>/dev/null

    # modify system log web page to add filtering capabilities
    Mod_Syslog_Asp install

    # Copy default logFilter.json file
    if [ ! -f "$CUSTOM_LOGFILTER_PATH" ]; then 
        log_msg "Green" "   - Copying Asus's default system log filtering file, in case user wants to customize defaults"
        cp "${DEFAULT_LOGFILTER_PATH}" "${SCRIPT_NAME_DIR}/"
    fi

    Mount_Control_Logfilter install

    # Add symlink for presets
    mkdir /www/user/modsyslogui  # first, need to create directory for symlink to live in
    ln -sf /jffs/addons/modsyslogui/presets.conf /www/user/modsyslogui/presets.json

} # end of Auto_Startup()

Mod_ServiceEvent() {
    # Parameters: $1 - install or uninstall
    case $1 in
        'install')
            log_msg "Green" "   - Adding ${SCRIPT_NAME} service-event line"
            # check if a service-event file exists and process as follows
			if [ -f /jffs/scripts/service-event ]; then
                # delete any existing modsyslogui lines just in case
                sed -i -e '/'"${SCRIPT_NAME}"'/d' /jffs/scripts/service-event
                echo '[ "$2" = modsyslogui ] && '"${PRESET_MANAGER}"' & # added by '"${SCRIPT_NAME}" >> /jffs/scripts/service-event
			# a service-event file did not exist, so create one
            else
				echo "#!/bin/sh" > /jffs/scripts/service-event
                echo " " >> /jffs/scripts/service-event
                echo '[ "$2" = modsyslogui ] && '"${PRESET_MANAGER}"' & # added by '"${SCRIPT_NAME}" >> /jffs/scripts/service-event
				chmod 0755 /jffs/scripts/service-event
			fi
        ;;
        'uninstall')
			log_msg "Green" "   - Removing ${SCRIPT_NAME} from service-event"
            # check if service-event line exists and if so, remove any lines found
            sed -i -e '/'"${SCRIPT_NAME}"'/d' /jffs/scripts/service-event
        ;;
    esac
} # end of Mod_ServiceEvent()

Mod_Syslog_Asp() {
    # Parameters: $1 install or uninstall
    case $1 in
        install)
            # Make sure asp files exists in /tmp
            if [ ! -f ${CUSTOM_SYSLOG_ASP_FILE} ]; then
                log_msg "Green" "   - Copying Asus's default Syslog ASP page, for adding in custom filtering capabilities"
                cp "${DEFAULT_SYSLOG_ASP_FILE}" "$TMP_DIR/"
            fi
            log_msg "Green" "   - Adding filtering capabilities to System Log UI page"
            # check and remove any existing custom code added by this addon
            sed -i '/\/\/++ Start custom function/,/\/\/++ End custom function/d' ${CUSTOM_SYSLOG_ASP_FILE}
            sed -i '/\/\/++ Start Custom UI/,/\/\/++ End Custom UI/d' ${CUSTOM_SYSLOG_ASP_FILE}
            # insert custom filtering globals, vars, and helpers
            sed -i "/^<script>$/r ${CUSTOM_FUNCTION_FILE}" ${CUSTOM_SYSLOG_ASP_FILE}
            # remove the default log record handling function
            sed -i '/var logString = htmlEnDeCode/,/setTimeout(get_log_data, 3000);/d' ${CUSTOM_SYSLOG_ASP_FILE}
            sed -i "/success: function(response){/r ${CUSTOM_FILTER_FILE}" ${CUSTOM_SYSLOG_ASP_FILE}

            # insert custom ui xml codeing 
            sed -i "/onclick=\"applySettings();\"/r ${CUSTOM_UI_FILE}" "${CUSTOM_SYSLOG_ASP_FILE}" #v1.0.1 changed insertion point
            # mount the customized web page with filtering capabilities added
            mount -o bind ${CUSTOM_SYSLOG_ASP_FILE} ${DEFAULT_SYSLOG_ASP_FILE}
        ;;
        uninstall)
            log_msg "Green" "   - Removing filtering capabilities from System Log UI page"
            ##----------------------------------------------##
            ## v1.0.2 unmount customized System Log UI page ##
            ##----------------------------------------------##
            if grep -q " ${SYSLOGPAGE_MP} " /proc/mounts; then
                while grep -q " ${SYSLOGPAGE_MP} " /proc/mounts; do # unmount multiples, in case more than 1
                    umount "${SYSLOGPAGE_MP}" 2>/dev/null || break
                done
            fi
            rm "$CUSTOM_SYSLOG_ASP_FILE"
        ;;
    esac
} # end of Mod_Syslog_Asp()

##----------------------------------------------------------------------##
## v1.0.2 added function to control mounting / unmounint logFilter.json ##
##----------------------------------------------------------------------##
Mount_Control_Logfilter () {
    # Parameters: $1 install or uninstall
    case $1 in
        install)
            log_msg "Green" "   - Mounting logFilter.json"
            mount -o bind ${CUSTOM_LOGFILTER_PATH} ${DEFAULT_LOGFILTER_PATH}
        ;;
        uninstall)
            log_msg "Green" "   - Removing customized logFilter.json"
            if grep -q " ${LOGFILTER_MP} " /proc/mounts; then
                while grep -q " ${LOGFILTER_MP} " /proc/mounts; do # remove multiples, just in case more than one mounted
                    umount "${LOGFILTER_MP}" 2>/dev/null || break
                done
            fi
        ;;
    esac
} # end of Mount_Control_Logfilter

Setup_Aliases() {
    # Parameters: $1 - install or uninstall
    # shortcuts to launching script
    case $1 in
        'install')
            # remove shell alias
            local cmdline
            if [ -d /opt/bin ]; then
                # Entware is installed, so setup link to /opt/bin
                log_msg "Green" "   - Adding ${SCRIPT_NAME} command line alias"
                ln -sf "${SCRIPT_INSTALL_PATH}" "/opt/bin/${SCRIPT_NAME}"
            else
                # Setup shell alias
                log_msg "Green" "   -  Adding ${SCRIPT_NAME} alias in profile.add"
                sed -i "/alias ${SCRIPT_NAME}/d" /jffs/configs/profile.add 2>/dev/null
                cmdline="alias ${SCRIPT_NAME}=\"sh ${SCRIPT_INSTALL_PATH}\" # ${SCRIPT_NAME} Addition"
                echo "${cmdline}" >> /jffs/configs/profile.add
            fi
        ;;
        'uninstall')
            # remove alias from profile.add. Brute force, meaning not checking to see if exists first, just assume and delete
            if [ -L /opt/bin/${SCRIPT_NAME} ]; then
                # Entware is installed, so setup link to /opt/bin
                log_msg "Green" "   - Deleting ${SCRIPT_NAME} command line alias"
                rm "/opt/bin/${SCRIPT_NAME}"
            else
                # Remove alias from profile.add
                if [ -f /jffs/configs/profile.add ]; then
                    STARTUPLINECOUNT=$(grep -c '# '"${SCRIPT_NAME}" /jffs/configs/profile.add)
                    if [ "${STARTUPLINECOUNT}" -gt 0 ]; then
                        log_msg "Green" "   -  Deleting ${SCRIPT_NAME} alias in profile.add"
                        sed -i -e '/# '"${SCRIPT_NAME}"'/d' /jffs/configs/profile.add
                    fi
                fi
            fi  
        ;;
    esac
} #  end of Setup_Aliases()

Custom_Settings(){
    # Parameters: $1 - install or uninstall
    # Add / delete a name space in the Asuswrt third party addons custome_settings.txt file
    case $1 in
        install)
            log_msg "Green" "   - Creating ${SCRIPT_NAME_DISPLAY} cusotom_settings.txt name space"
            # check if any previous name space entries exist and remove them
			if [ -f ${SETTINGS_FILE} ]; then
				STARTUPLINECOUNT=$(grep -c "${SCRIPT_NAME_DISPLAY}" ${SETTINGS_FILE})
				# delete existing comment line if it exists - cleanup any residual stuff
				if [ "${STARTUPLINECOUNT}" -gt 0 ]; then
					sed -i -e  '/'"${SCRIPT_NAME_DISPLAY}"'/d' ${SETTINGS_FILE}
                    am_settings_set "${SCRIPT_NAME_DISPLAY}"_ver "${SCRIPT_VERSION}"
				else
                    am_settings_set "${SCRIPT_NAME_DISPLAY}"_ver "${SCRIPT_VERSION}"
				fi
			# a service-event file did not exist, so create one
            else
				am_settings_set "${SCRIPT_NAME_DISPLAY}"_ver "${SCRIPT_VERSION}"
			fi
        ;; 
        uninstall)
            log_msg "Green" "   - Deleting ${SCRIPT_NAME_DISPLAY} cusotom_settings.txt name space"
            # check if any previous name space entries exist and remove them
			if [ -f ${SETTINGS_FILE} ]; then
				STARTUPLINECOUNT=$(grep -c "${SCRIPT_NAME_DISPLAY}" ${SETTINGS_FILE})
				# delete existing comment line if it exists - cleanup any residual stuff
				if [ "${STARTUPLINECOUNT}" -gt 0 ]; then
					sed -i -e  '/'"${SCRIPT_NAME_DISPLAY}"'/d' ${SETTINGS_FILE}
				fi
            fi
        ;;
    esac
} # end of Custom_Settings()

Install() {
    # Parameter options: None
    # Install script and download webui file
    # This is also called by the update process once a new script is downloaded by update() function
    clear
    Scriptinfo

    log_msg "Green" "Installing ${SCRIPT_NAME_DISPLAY}"
    # shellcheck disable=SC2078
    if [ ! Check_Firmware ]; then
        log_msg "Red" "[ERROR] Addons are not supported in this routers firmware - script aborting!!!"
        Press_Enter
        rm -f "${0}" 2>/dev/nullf
        exit 5
    fi

    # Create the directory for this scripts addon files
    if [ ! -d "${SCRIPT_NAME_DIR}" ]; then
        log_msg "Green" "   - Creating ${SCRIPT_NAME} ADDON directory"
        mkdir -p "${SCRIPT_NAME_DIR}"
    else
        log_msg "Yellow" "   ${SCRIPT_NAME} is already installed or remnants of a previous install exist."
        log_msg "Yellow" "   >>> Proceeding will only replace existing files if there is a newer version, no harm otherwise."
        printf "\n"
        log_msg "Red" "   Are you certain you want to proceed? [y=Yes n=No]:"
        printf "\n"

        read -r yn
        printf "\n"
        if [ "${yn}" = "n" ] || [ "${yn}" = "N" ]; then
            log_msg "Cyan" "   - No Changes have been made"
            return 0
        else 
            ##----------------------------------------------------------------------##
            ## v1.0.2 unmount customized System Log Page asp and logFilter.json     ##
            ## added to avoid double mounting in case install is run more than once ##
            ##----------------------------------------------------------------------##
            Mod_Syslog_Asp uninstall 
            Mount_Control_Logfilter uninstall
        fi
    fi

    # Download all custom script files
    Download_Script_Files

    ##---------------------------------------------------------------------------------------------------------------##
    ## v1.0.2 added check if Main_LogStatus_Content.asp exists for this script, since install can run more than once ##
    ##---------------------------------------------------------------------------------------------------------------##
    if [ -f ${CUSTOM_SYSLOG_ASP_FILE} ]; then
        # remove existing customize asp file if exists
        log_msg "Green" "   - Deleting existing customized System Log page customizations"
        rm ${CUSTOM_SYSLOG_ASP_FILE} 
    fi

    # Copy default System Log ASP file to scripts addon directory
    log_msg "Green" "   - Copying Asus's default Syslog ASP page, for adding in custom filtering capabilities"
    cp "${DEFAULT_SYSLOG_ASP_FILE}" "$TMP_DIR/"

    # modify system log web page to add filtering capabilities
    Mod_Syslog_Asp install

    ##---------------------------------------------------------------------------------------------------##
    ## v1.0.2 added check if custom logFilter.json exists, so we don't overwrite existing customizations ##
    ## added this in case the install function is run more than once                                     ##
    ##---------------------------------------------------------------------------------------------------##
    if [ ! -f ${CUSTOM_LOGFILTER_PATH} ]; then
        # copy over the system's default logFilter.json file 
        #+ the defaults are fine, but copying over in case user wants to customize
        log_msg "Green" "   - Copying Asus's default system log filtering file, in case user wants to customize defaults"
        cp "${DEFAULT_LOGFILTER_PATH}" "${SCRIPT_NAME_DIR}/"
    fi
    ##------------------------------------------------------------------------##
    ## v1.0.2 added call to mount function, instead of mounting directly here ##
    ##------------------------------------------------------------------------##
    # mount logFilter.json
    Mount_Control_Logfilter install

    # add autostart_modsyslogui script to services-start, so the customized filtering is installed on router reboot
    Mod_Startup install
    
    # add alias command for invoking script
    Setup_Aliases install

    # create Asuswrt third party addon name space with version information
    Custom_Settings installl

    ##---------------------------------------------------##
    ## v1.1.0 add preset_manager.sh to service-event     ##
    ## for when addon-api is triggerd to add|edit|delete ##
    ## preset filters                                    ##
    ## --------------------------------------------------##
    Mod_ServiceEvent install

    ##-------------------------------------##
    ## v1.1.0 add symlink for presets.conf ##
    ##-------------------------------------##
    if [ ! -f ${WWW_PRESET_JSON} ]; then
		mkdir ${WWW_PRESET_DIR}  # first, need to create directory for symlink to live in
    	ln -sf ${PRESET_CONF} ${WWW_PRESET_JSON}
	fi

    ##-------------------------------------------##
    ## v1.1.0 make preset_manager.sh executeable ##
    ##-------------------------------------------##
    chmod +x ${PRESET_MANAGER}

    # Install complete messages
    log_msg "Green" "${SCRIPT_NAME_DISPLAY} installation complete!"
    ##--------------------------------------------------------------------------##
    ## v1.0.1 - added verbiage noting it is not necessary to edit the json file ##
    ##--------------------------------------------------------------------------##
    Magenta "   - tho not necessary (defaults are fine), run the EDIT command (menu option #5), to modify the logFilter.json to exclude additional Log records to your likings"
} # end of Install()

Uninstall() {
    log_msg "Green" "Uninstalling the ${SCRIPT_DISPLAY_NAME} script"

    # Remove the addons startup line in services-start
    Mod_Startup uninstall

    # unmount the custom logFilter.json file
    umount ${DEFAULT_LOGFILTER_PATH} 2>/dev/null

    # Remove UI custom code
    Mod_Syslog_Asp uninstall

    ##-------------------------------------------##
    ## v1.0.2 added unmount logFilter.json call ##
    ##-------------------------------------------##
    # Unmount any logFilter.json customizations
    Mount_Control_Logfilter uninstall

    # Remove the scripts alias, either under /opt/bin or in profiles.add
    Setup_Aliases uninstall

    # Remove the addons custom-settings.txt entry
    Custom_Settings uninstall

    ##------------------------------------------------------##
    ## v1.1.0 remove preset_manager.sh frin service-event   ##
    ## -----------------------------------------------------##
    Mod_ServiceEvent uninstall

    ##-------------------------------------------##
    ## v1.1.0 preset manager symlink + directory ##
    ##-------------------------------------------##
    rm -rf ${WWW_PRESET_DIR}

    # Remove the scripts addon directory
    log_msg "Green" "   - Removing the scripts addon directory"
	cd "${TMP_DIR}"
    rm -rf ${SCRIPT_NAME_DIR}

    # output completion message
    log_msg "Green" "Completed uninstalling the ${SCRIPT_DISPLAY_NAME} script"
} # end of Uninstall()

Update() {    
    if [ ! "$1" = "amtmupdate" ]; then # if running via amtmupdate, skip version checking - already done
        # Check for, and optionally apply updates.
        # Parameter options: check (do not update), silent (update without prompting)
        local updatestatus yn remotever
        Scriptinfo
        log_msg "Green" "Checking for updates"
        # Update the webui status thorugh detect_update.js ajax call.
        # Get the version of the script on Github
        localver="$(grep "SCRIPT_VERSION=" ${SCRIPT_INSTALL_PATH} | grep -m1 -oE "${scriptVersRegExp}")"
        remotever="$(curl -fsL --retry 4 --retry-delay 5 "${GIT_URL}/${SCRIPT_NAME}" | grep "SCRIPT_VERSION=" | grep -m1 -oE "${scriptVersRegExp}")"
        # Compare local and remote versions to see how to proceed
        if [ "${localver}" != "${remotever}" ]; then
            # version upgrade
            updatestatus="Update"
        else
            updatestatus="NoUpdate"
        fi

        case "${updatestatus}" in
        'NoUpdate')
            log_msg "Green" "   - You have the latest version installed"
            printf " Would you like to overwrite your existing installation anyway? [y=Yes n=No]: "
            ;;
        'Update')
            # New Version Number
            log_msg "Green" "   - ${SCRIPT_NAME_DISPLAY} ${updatestatus} is now available!"
            printf " Would you like to update now? [y=Yes n=No]: "
            ;;
        *)
            log_msg "Red" "   - Error occured checking version information"
            Press_Enter
            return
            ;;
        esac
        read -r yn
        printf "\n"
        if [ "${yn}" = "n" ] || [ "${yn}" = "N" ]; then
            log_msg "Cyan" "   - No Changes have been made"
            return 0
        fi
    fi

	Mod_Syslog_Asp uninstall   # Disable - Remove filtering mod from System Log UI
    Download_Script_Files      # Download all associated files
    Mod_Syslog_Asp install     # Re-Enable - Add filtering mod back to System Lot UI
    
    # Output completion message
    log_msg "Green" "Completed installing script updates"
    return 0
} # end of Update()

##---------------------------------##
## v1.2.0 amtmupdate functionality ##
##---------------------------------##
Update_FromAMTM()
{
    if ! "$ENABLE_AMTMUPDATE"
    then
        log_msg "Yellow" "Automatic script updates via AMTM are currently disabled."
        return 1
    fi
    if [ $# -gt 0 ] && [ "$1" = "check" ]
    then return 0
    fi
    log_msg "Cyan" "$SCRIPT_NAME_DISPLAY Running amtmupdate"
    AMTMUPDATE_RUN_FLAG=true     # set amtmupdate run flag to true, so we can minimize console output
    Update amtmupdate
    return "$?"
} # end Update_FromAMTM()

Edit () {
    local before_hash 
    local after_hash 

    # Get the hash of the hidemenus list file BEFORE editing
    before_hash=$(sha256sum "${CUSTOM_LOGFILTER_PATH}" | awk '{ print $1 }')

    # Make sure the custom logFilter file exists, if not, copy it over
    if [ ! -f "${CUSTOM_LOGFILTER_PATH}" ]; then
        cp ${DEFAULT_LOGFILTER_PATH} ${CUSTOM_LOGFILTER_PATH}
    fi

    nano ${CUSTOM_LOGFILTER_PATH}

    # Get the hash of the hidemenus list file AFTER editing
    after_hash=$(sha256sum "${CUSTOM_LOGFILTER_PATH}" | awk '{ print $1 }') 

    # Check for any changes
    if [ ! "${before_hash}" = "${after_hash}" ]; then
        mount -o bind ${CUSTOM_LOGFILTER_PATH} ${DEFAULT_LOGFILTER_PATH}
        log_msg "Yellow" "Your changes have been saved to ${CUSTOM_LOGFILTER_PATH} and applied to the System"
    else
        log_msg "Yellow" "No changes were made to the ${CUSTOM_LOGFILTER_PATH}"
    fi
} # end of Edit()

Disable_Filter () {
    Mod_Syslog_Asp uninstall
} # end of Remove_Filter()

Enable_Filter () {
    Mod_Syslog_Asp install
} # end of Add_Filter()

###---###---###---###---###---###---###---###---###---###---###---###---###---###---###---###---###
## Script Mainline
clear >&3 # v1.1.0 - added redirection (>3) to keep output on screen after adding debug to log functionality

# Detect if script is run from an SSH shell interactively or from the WebUI (unattended)
if tty >/dev/null 2>&1; then
    mode="interactive"
else
    mode="unattended"
fi

# check to make sure only one argument passed, exit otherwise
if [ $# -gt 2 ]; then
    log_msg "Red" "Too many arguments ($#) passed to this script!"
    if [ $mode = "interactive"]; then
        printf "\n"
        Show_ArgsHelp
    fi
    exit 1
fi

##-------------------------------------##
## v1.0.1 added firmware version check ##
##-------------------------------------##
# Exit if not running a supported firmware version 
if ! ${SUPPORTED_FIRMWARE_VERSION}; then
    log_msg "Red" "Firmware version ${fwInstalledBranchVer} not suppoted - exiting script"
    exit 5
fi

##---------------------------------------------------##
## v1.2.0 added logic flow capabilitiy,              ##
## for when files need to be added / removed         ##
## or changes needed to startup or service event,    ##
## that can't be handled by the normal update prcess ##
##---------------------------------------------------##

if [ ! -f "$CURRENT_FLOW_FILE" ]; then
    # code in this section can / will be changed depending on current logic flow needs

    # remove legacy (pre v1.2.0) files
    rm "${SCRIPT_NAME_DIR}/autostart_modsyslogui"
    rm "${SCRIPT_NAME_DIR}/Main_LogStatus_Content.asp"
    sed -i 's/autostart_modsyslogui/autostartup/' /jffs/scripts/services-start

    rm -f "$LAST_FLOW_FILE" 2>/dev/null    #remove that last flow version file
    touch "$CURRENT_FLOW_FILE"
fi

# Make sure the version in custom_settings.txt matches the version of this script
if [ "$(am_settings_get "${SCRIPT_NAME_DISPLAY}"_ver)" != "${SCRIPT_VERSION}" ]; then
	am_settings_set "${SCRIPT_NAME_DISPLAY}"_ver "${SCRIPT_VERSION}"
fi

# Check and process the argument passed when calling this script
case "${1}" in
    'menu'|'') Main_Menu ;;
    'install') Install; Press_Enter; Main_Menu ;; #v1.0.2 - added Press_Enter and Main_Menu to avoid exiting script
    'update') Update ;;
    'disable') Disable_Filter ;;
    'enable') Enable_Filter ;;
    'uninstall') Uninstall ;;
    'amtmupdate') shift; Update_FromAMTM "$@"; exit "$?";; #v1.2.0 - amtmupdate functionality
    'autostartup') Auto_Startup ;; #v1.2.0 - changed router startup process, due to change of asp location to /tmp
    *) log_msg "Red" "${1} is an unknown argument"; exit 1 ;;
esac
